### ISSUE TITLE
php 7.4 on macos

### ISSUE THREAD

**Issue by if4lcon** [phpbrew/phpbrew#1040]
Alternatively, you may set the environment variables OPENSSL_CFLAGS

and OPENSSL_LIBS to avoid the need to call pkg-config.

See the pkg-config man page for more details.

no matter what command I changed I even copied php 7.3 configure parameters from homebrew

**Comment by bskiefer** [comment]
Not sure if this helps in your case, but my fix was to add the following to my `.bashrc`/`.zshrc` file.

```
CPPFLAGS=-I/usr/local/opt/openssl/include:"${CPPFLAGS}"  
LD_LIBRARY_PATH=/usr/local/Cellar/openssl/1.0.2s/lib:"${LD_LIBRARY_PATH}"
CPATH=/usr/local/opt/openssl/include:"${CPATH}"  
PKG_CONFIG_PATH=/usr/local/Cellar/openssl/1.0.2s/lib/pkgconfig:"${PKG_CONFIG_PATH}"          
export LD_LIBRARY_PATH CPATH PKG_CONFIG_PATH CPPFLAGS
```

May have to adjust as necessary, but as you can tell I'm using brew's openssl for pkg config & LD.

**Comment by if4lcon** [comment]
thank you ... unfortunately didn't compile

```
Alternatively, you may set the environment variables SASL_CFLAGS

and SASL_LIBS to avoid the need to call pkg-config.

See the pkg-config man page for more details.```

**Comment by ramsey** [comment]
I'm having the same problem. It looks like phpbrew can no longer find the Homebrew libraries.

**Comment by bskiefer** [comment]
@ramsey What error are you getting? It's sometimes useful to run `brew link {{package}} --force`, or reinstalling the dependency. However I had to liter my .zshrc with exports to get everything to work correctly.

I'll just include a few that solved my issues

```

export CPPFLAGS=-I/usr/local/opt/openssl/include:"${CPPFLAGS}"  
export CPPFLAGS=-I/usr/local/opt/libedit/include:"${CPPFLAGS}"  
export CPPFLAGS=-I/usr/local/Cellar/readline/8.0.1/include:"${CPPFLAGS}"  

export LD_LIBRARY_PATH=/usr/local/Cellar/openssl/1.0.2s/lib:"${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH=/usr/local/opt/libedit/lib:"${LD_LIBRARY_PATH}"  
export LD_LIBRARY_PATH=/usr/local/Cellar/readline/8.0.1/lib:"${LD_LIBRARY_PATH}" 

export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/opt/libedit/lib/pkgconfig
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/Cellar/readline/8.0.1/lib/pkgconfig

export EXTRA_LIBS="/usr/local/Cellar/readline/8.0.1/lib/libhistory.dylib 
/usr/local/Cellar/readline/8.0.1/lib/libreadline.dylib"

```

Which now works with the following config.yaml

```
variants:
    dev:
        bcmath:
        calendar:
        cli:
        ctype:
        dom:
        fileinfo:
        filter:
        ipc:
        iconv:
        json:
        mbregex:
        mbstring:
        mhash:
        mcrypt:
        pcntl:
        pcre:
        pdo:
        phar:
        posix:
        sockets:
        tokenizer:
        xml:
        curl:
        openssl:
        zip:
        gd:
          - --with-gmp=/usr/local/opt
          - --with-openssl
          - --enable-gd
          - --with-zlib-dir=/usr/local/opt/zlib
          - --enable-xml
          - --enable-libxml
          - --with-gd
          - --with-readline=/opt/local
          - --with-iconv=/opt/local
extensions:
    dev:
        xdebug: stable
        redis: stable
```

**Comment by ramsey** [comment]
If I export all the variables like that, it works. It's just strange that this is needed now. Did something change in Homebrew or macOS that keeps phpbrew from being able to find these libs?

**Comment by bskiefer** [comment]
Are you getting the PKG_CONFIG errors?

**Comment by markwu** [comment]
I got the same error. I can't compile php-7.4.0 on my mac either.

**Comment by markwu** [comment]
I used to use the following command to compile my php

```bash
phpbrew install 7.3.12 +default +dbs +dba +openssl +apxs2 +bz2=/usr/local/opt/bzip2 +zlib=/usr/local/opt/zlib`
```

No idea what's going on.

**Comment by markwu** [comment]
> If I export all the variables like that, it works. It's just strange that this is needed now. Did something change in Homebrew or macOS that keeps phpbrew from being able to find these libs?

I think PHP change their configure and makefile for php-7.4.0. php-7.3.12 can compiled by phpbrew without any problems.

**Comment by morozov** [comment]
There are indeed [quite a few changes](https://github.com/phpbrew/phpbrew/issues?q=is%3Aissue+label%3A%22PHP+7.4%22+milestone%3A%22Release+1.24.0%22) in the PHP 7.4 flags that were addressed in [Release 1.24.0](https://github.com/phpbrew/phpbrew/releases/tag/1.24.0). Please be aware that it has a bug that makes it incompatible with PHP 7.2 and older. The patch release that fixes this bug is coming.

**Comment by markwu** [comment]
I tried Release 1.24.1,  no luck. I still get the same errors.

**Comment by morozov** [comment]
@markwu I don't use macOS, so I won't be able to help you at this stage. Also, I'm not familiar with how exactly PHPBrew integrates with the dependencies provided by Homebrew.

The error you're seeing may happen more than once during PHP installation:
```
$ grep "Alternatively, you may set the environment variables OPENSSL_CFLAGS" ~/.phpbrew/build/php-7.4.0/configure
Alternatively, you may set the environment variables OPENSSL_CFLAGS
Alternatively, you may set the environment variables OPENSSL_CFLAGS
Alternatively, you may set the environment variables OPENSSL_CFLAGS
Alternatively, you may set the environment variables OPENSSL_CFLAGS
Alternatively, you may set the environment variables OPENSSL_CFLAGS
Alternatively, you may set the environment variables OPENSSL_CFLAGS
Alternatively, you may set the environment variables OPENSSL_CFLAGS
Alternatively, you may set the environment variables OPENSSL_CFLAGS
```
If you want to troubleshoot the issue, you can instrument your `configure` file with debug `echo` statements, run `./configure` with the same flags as PHPBrew does and see where exactly and why the error is displayed.

Then you can compare the `configure` files for PHP 7.3 and 7.4 and find the difference which makes those messages displayed.

**Comment by markwu** [comment]
I tried configure, no luck ... are there any ways can assign environment variables during compiled time through phpbrew?

I saw homebrew php formula assign the following environment variables during compile time

```ruby
    ENV["KERBEROS_CFLAGS"] = " "
    ENV["KERBEROS_LIBS"] = "-lkrb5"
    ENV["SASL_CFLAGS"] = "-I#{MacOS.sdk_path_if_needed}/usr/include/sasl"
    ENV["SASL_LIBS"] = "-lsasl2"
    ENV["EDIT_CFLAGS"] = " "
    ENV["EDIT_LIBS"] = "-ledit"
```

Mayby, I can do the same way that homebrew does.

**Comment by MehGokalp** [comment]
if you're using brew you can see the pkg usage information with;
`brew info openssl`

> openssl@1.1: stable 1.1.1d (bottled) [keg-only]
> Cryptography and SSL/TLS Toolkit
> https://openssl.org/
> /usr/local/Cellar/openssl@1.1/1.1.1d (7,983 files, 17.9MB)
>   Poured from bottle on 2019-11-29 at 14:10:15
> From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/openssl@1.1.rb
> ==> Caveats
> A CA file has been bootstrapped using certificates from the system
> keychain. To add additional certificates, place .pem files in
>   /usr/local/etc/openssl@1.1/certs
> 
> and run
>   /usr/local/opt/openssl@1.1/bin/c_rehash
> 
> openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
> because openssl/libressl is provided by macOS so don't link an incompatible version.
> 
> If you need to have openssl@1.1 first in your PATH run:
>   echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc
> 
> For compilers to find openssl@1.1 you may need to set:
>   export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
>   export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
> 
> For pkg-config to find openssl@1.1 you may need to set:
>   export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

as you can see in the last line: "For pkg-config to find openssl@1.1 you may need to set:"
run
`export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"`

and it will work.

**Comment by markwu** [comment]
@MehGokalp 

``` bash
$ export PKG_CONFIG_PATH="$(brew --prefix openssl)"/lib/pkgconfig:"${PKG_CONFIG_PATH}"
$ phpbrew install 7.4.0 +default +dbs +dba +openssl +apxs2 +bz2="$(brew --prefix bzip2)" +zlib="$(brew --prefix zlib)"
```

I tried your suggestions, it configure without any problems, but I got the message when it start to make

```
make: *** No rule to make target `libs/libphp7.4.0.bundle', needed by `all'.  Stop.
```

**Comment by acrobat** [comment]
@markwu I think this is related to the [apache2module patch](https://github.com/phpbrew/phpbrew/blob/9267098cb6416375408bea941ce191e659040723/src/PhpBrew/Patches/Apache2ModuleNamePatch.php#L53) phpbrew runs. In previous php versions the `Makefile.global` was included in the root dir, but in [php 7.4 they have moved](https://github.com/php/php-src/pull/3915) it to build. 

So I guess adding it to the apache module patch should make sure it works on old and new versions of php.

```
$rules[] = RegExpPatchRule::files(array('Makefile.global', 'build/Makefile.global'))
```

**Comment by markwu** [comment]
@acrobat Thanks for your advise. Now, I can compile php-7.4.0 with phpbrew 1.24.1.

But it's still quite annoying, I have to export additional environment variables outside phpbrew.

**Comment by markwu** [comment]
I can build 7.4, 7.3, 7.2 with phpbrew 1.24.1, but failed to build 5.6 due to openssl version.

it seems php5.6 only build with openssl 1.0 instead of 1.1.

**Comment by markwu** [comment]
After some investigations of PatchRule, It seems I have to split `Apache2ModuleNamePatch.php` patch to 2 files, one for php <= 7.3.x and one for php >= 7.4.x. Or, I will always get error messages when build.

For php <= 7.3.x, with the rule:
```php
$rules[] = RegExpPatchRule::files(array('Makefile.global'))
```
For php >= 7.4.x, with the rule:
```php
$rules[] = RegExpPatchRule::files(array('build/Makefile.global'))
```

@morozov How do you think?

**Comment by markwu** [comment]
I already did it in my fork, if you think it's okay, i'll create a PR for this.

**Comment by morozov** [comment]
I think we should add a constructor argument to the patch class instead. Like:
```php
class Apache2ModuleNamePatch
{
    private $targetPhpVersion;

    function __construct($targetPhpVersion) {}
}
```

**Comment by markwu** [comment]
Even we have `$targetPhpVersion` inside patch class, the patch still for a specific (group of) version only. In this case  `Apache2ModuleNamePatch` need to apply to both 7.3 and 7.4 with different rules, one for `Makefile.global` and another one for `build/Makefile.global`.

How can I do this with `$targetPhpVersion`? Could you elaborate more details?

Thanks.

**Comment by morozov** [comment]
Please see the updated comment above.

**Comment by markwu** [comment]
Okay, I known what you mean, how about we change to following, just pass $build and $logger to rules? It's more clear.

```php
class Patch
{
    ....
    abstract public function rules(Buildable $build, Logger $logger);

    public function apply(Buildable $build, Logger $logger)
    {
        $cnt = 0;
        if ($rules = $this->rules($build, $logger)) {
            // todo: should backup all files in one time (some patch rules have the same file names)
            foreach ($rules as $rule) {
                $rule->backup($build, $logger);
            }
            foreach ($rules as $rule) {
                if ($patched = $rule->apply($build, $logger)) {
                    $cnt += $patched;
                }
            }
        }

        return $cnt;
    }
}

class Apache2ModuleNamePatch extends Patch
{
    ....
    public function rules(Buildable $build, Logger $logger)
    {
        if (version_compare($build->getVersion, '7.4') >= 0) {
            // rules for PHP 7.4 and newer
        } else {
            // rules for PHP 7.3 and older
        }
    }
}
```

**Comment by markwu** [comment]
Finally, I figure out how to compile macOS PHP with phpbrew. In php 7.4 they change their configure, they will only get the path of openssl/libxml2/curl from pkg-config. Therefore we need to export PKG_CONFIG_PATH in shell if you don't use default system openssl/libxml2/curl.

For some extensions, they don't support pkg-config, so, we need to export LDFLAGS and CPPFLAGS.

With the following command, I can build php 7.4.0  with phpbrew 1.24.1( with apache module name fix from my fork).

```
# for php 7.4.0 build
$export PKG_CONFIG_PATH="$(brew --prefix openssl@1.1)"/lib/pkgconfig:"${PKG_CONFIG_PATH}"
$export PKG_CONFIG_PATH="$(brew --prefix libxml2)"/lib/pkgconfig:"${PKG_CONFIG_PATH}"
$export PKG_CONFIG_PATH="$(brew --prefix curl-openssl)"/lib/pkgconfig:"${PKG_CONFIG_PATH}"

# if you use curl, not curl-openssl
$export PKG_CONFIG_PATH="$(brew --prefix curl-openssl)"/lib/pkgconfig:"${PKG_CONFIG_PATH}"

# for ftp extension build
$export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
$export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

# build php 7.4.0
phpbrew --debug install --jobs "$(nproc)" 7.4.0 +default +dbs +dba +apxs2 +bz2="$(brew --prefix bzip2)" +zlib="$(brew --prefix zlib)"

# build extension
phpbrew ext install gettext -- --with-gettext="$(brew --prefix gettext)" && phpbrew ext install iconv -- --with-iconv="$(brew --prefix libiconv)" && phpbrew ext install ftp -- --with-openssl-dir="$(brew --prefix openssl@1.1)" && phpbrew ext install exif && phpbrew ext install soap && phpbrew ext install gd -- --with-gd=shared --with-zlib-dir="$(brew --prefix zlib)" && phpbrew ext install opcache && phpbrew ext install xdebug && phpbrew ext install github:nikic/php-ast
```

With the following command, I can build php 5.6.x and php 7.1.x, 7.2.x, 7.3.x  with phpbrew 1.24.1(with openssl 1.1 for PHP56 fix from my fork).  I did not test  7.0.x.

```bash
# build php 7.4.0
phpbrew --debug install --jobs "$(nproc)" 7.3.12 +default +dbs +dba +apxs2 +bz2="$(brew --prefix bzip2)" +zlib="$(brew --prefix zlib)"

# build extension
phpbrew ext install gettext -- --with-gettext="$(brew --prefix gettext)" && phpbrew ext install iconv -- --with-iconv="$(brew --prefix libiconv)" && phpbrew ext install ftp -- --with-openssl-dir="$(brew --prefix openssl@1.1)" && phpbrew ext install exif && phpbrew ext install soap && phpbrew ext install gd -- --with-gd=shared --with-zlib-dir="$(brew --prefix zlib)" && phpbrew ext install opcache && phpbrew ext install xdebug && phpbrew ext install github:nikic/php-ast
```

**Comment by Timandes** [comment]
According to @markwu 's comments, installing `+neutral` PHP-7.4 can do as follows:

```shell
brew install pkg-config

brew install libxml2
export PKG_CONFIG_PATH="$(brew --prefix libxml2)"/lib/pkgconfig:"${PKG_CONFIG_PATH}"

brew install libiconv

phpbrew install 7.4.0 +neutral -- --with-iconv=`brew --prefix libiconv`

```

**Comment by morozov** [comment]
Fixed by #1085.

**Comment by ttodua** [comment]
for future readers  - `sudo apt-get install libxml2-dev` fixes for ubuntu in some cases.

**Comment by caizhichao** [comment]
export LDFLAGS="-L/usr/local/opt/openssl/lib"
   export CPPFLAGS="-I/usr/local/opt/openssl/include"
   export PKG_CONFIG_PATH=/usr/local/Cellar/openssl@1.1/1.1.1k/lib/pkgconfig
   I meet with the same problem in MacOS, when i set the command above, i can install php 8.1.27 rightly,  luckly.
