### ISSUE TITLE
v2.0.0 doesn't appear to pass parameters on to ./configure

### ISSUE THREAD

**Issue by MagicLegend** [phpbrew/phpbrew#1316]
### Output

```
$ phpbrew ext install ssh2 -- --with-ssh2=$(brew --prefix libssh2)
Downloading https://pecl.php.net/rest/r/ssh2/stable.txt via curl extension
[==================================================================] 4.00/4.00B 100%
Downloading https://pecl.php.net/rest/r/ssh2/0.13.xml via curl extension
[==================================================================] 1.23/1.23KB 100%
Downloading https://pecl.php.net/rest/r/ssh2/stable.txt via curl extension
[==================================================================] 4.00/4.00B 100%
Downloading https://pecl.php.net/rest/r/ssh2/0.13.xml via curl extension
[==================================================================] 1.23/1.23KB 100%
Downloading http://pecl.php.net/get/ssh2-0.13.tgz via curl extension
[==================================================================] 28.30/28.30KB 100%
===> Extracting to /Users/<user>/.phpbrew/build/php-7.4.27/ext...
===> Installing ssh2 extension...
Log stored at: /Users/<user>/.phpbrew/build/php-7.4.27/ext/ssh2/build.log
Changing directory to /Users/<user>/.phpbrew/build/php-7.4.27/ext/ssh2
===> Phpize...
===> Configuring...
Error: Command failed: ./configure '--with-php-config=/Users/<user>/.phpbrew/php/php-7.4.27/bin/php-config' >> '/Users/<user>/.phpbrew/build/php-7.4.27/ext/ssh2/build.log' 2>&1 returns:
```

**Note that the error is not returned, it's only visible in the log file**

When using phpbrew v1.28.0 it's fine, and will correctly take the location of `libssh2` out of the arguments. Thus I'm suspecting this bug is only present on v2.0.0.

### Expected Result

Successful installation.

### Command

Paste your phpbrew install command here (be sure to install with `--debug` flag, e.g. `phpbrew --debug install`)

`phpbrew ext install ssh2 beta -- --with-ssh2=$(brew --prefix libssh2)`

Command that works (when manually pointing to the v1 phar): 

`./phpbrew-1.28.0.phar extension install ssh2 beta -- --with-ssh2=$(brew --prefix libssh2) --prefix=$(brew --prefix libssh2)`

### Build Log

<details>
  <summary>build.log</summary>

```
Configuring for:
PHP Api Version:         20190902
Zend Module Api No:      20190902
Zend Extension Api No:   320190902
configure.ac:18: warning: $as_echo is obsolete; use AS_ECHO(["message"]) instead
build/php.m4:2110: PHP_CONFIG_NICE is expanded from...
configure.ac:18: the top level
configure.ac:161: warning: The macro `AC_LANG_C' is obsolete.
configure.ac:161: You should run autoupdate.
./lib/autoconf/c.m4:72: AC_LANG_C is expanded from...
build/libtool.m4:2727: _LT_AC_LANG_C_CONFIG is expanded from...
build/libtool.m4:2726: AC_LIBTOOL_LANG_C_CONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: The macro `AC_LANG_C' is obsolete.
configure.ac:161: You should run autoupdate.
./lib/autoconf/c.m4:72: AC_LANG_C is expanded from...
lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
./lib/autoconf/general.m4:2270: AC_CACHE_CHECK is expanded from...
build/libtool.m4:561: _LT_AC_LOCK is expanded from...
build/libtool.m4:1184: AC_LIBTOOL_SYS_HARD_LINK_LOCKS is expanded from...
build/libtool.m4:2727: _LT_AC_LANG_C_CONFIG is expanded from...
build/libtool.m4:2726: AC_LIBTOOL_LANG_C_CONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: The macro `AC_TRY_LINK' is obsolete.
configure.ac:161: You should run autoupdate.
./lib/autoconf/general.m4:2920: AC_TRY_LINK is expanded from...
lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
./lib/autoconf/general.m4:2270: AC_CACHE_CHECK is expanded from...
build/libtool.m4:561: _LT_AC_LOCK is expanded from...
build/libtool.m4:1184: AC_LIBTOOL_SYS_HARD_LINK_LOCKS is expanded from...
build/libtool.m4:2727: _LT_AC_LANG_C_CONFIG is expanded from...
build/libtool.m4:2726: AC_LIBTOOL_LANG_C_CONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: back quotes and double quotes must not be escaped in: $as_me:${as_lineno-$LINENO}: WARNING: \`$CC' does not support \`-c -o', so \`make -j' may be unsafe
build/libtool.m4:1184: AC_LIBTOOL_SYS_HARD_LINK_LOCKS is expanded from...
build/libtool.m4:2727: _LT_AC_LANG_C_CONFIG is expanded from...
build/libtool.m4:2726: AC_LIBTOOL_LANG_C_CONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: back quotes and double quotes must not be escaped in: $as_me: WARNING: \`$CC' does not support \`-c -o', so \`make -j' may be unsafe
build/libtool.m4:1184: AC_LIBTOOL_SYS_HARD_LINK_LOCKS is expanded from...
build/libtool.m4:2727: _LT_AC_LANG_C_CONFIG is expanded from...
build/libtool.m4:2726: AC_LIBTOOL_LANG_C_CONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: back quotes and double quotes must not be escaped in: $as_me:${as_lineno-$LINENO}: WARNING: output file \`$ofile' does not exist
build/libtool.m4:1917: _LT_AC_TAGCONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: back quotes and double quotes must not be escaped in: $as_me: WARNING: output file \`$ofile' does not exist
build/libtool.m4:1917: _LT_AC_TAGCONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: back quotes and double quotes must not be escaped in: $as_me:${as_lineno-$LINENO}: WARNING: output file \`$ofile' does not look like a libtool script
build/libtool.m4:1917: _LT_AC_TAGCONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: back quotes and double quotes must not be escaped in: $as_me: WARNING: output file \`$ofile' does not look like a libtool script
build/libtool.m4:1917: _LT_AC_TAGCONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: back quotes and double quotes must not be escaped in: $as_me:${as_lineno-$LINENO}: WARNING: using \`LTCC=$LTCC', extracted from \`$ofile'
build/libtool.m4:1917: _LT_AC_TAGCONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: back quotes and double quotes must not be escaped in: $as_me: WARNING: using \`LTCC=$LTCC', extracted from \`$ofile'
build/libtool.m4:1917: _LT_AC_TAGCONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: back quotes and double quotes must not be escaped in: tag name \"$tagname\" already exists
build/libtool.m4:1917: _LT_AC_TAGCONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: The macro `AC_LANG_CPLUSPLUS' is obsolete.
configure.ac:161: You should run autoupdate.
./lib/autoconf/c.m4:262: AC_LANG_CPLUSPLUS is expanded from...
build/libtool.m4:2809: _LT_AC_LANG_CXX_CONFIG is expanded from...
build/libtool.m4:2808: AC_LIBTOOL_LANG_CXX_CONFIG is expanded from...
build/libtool.m4:1917: _LT_AC_TAGCONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: back quotes and double quotes must not be escaped in: $as_me:${as_lineno-$LINENO}: WARNING: \`$CC' does not support \`-c -o', so \`make -j' may be unsafe
build/libtool.m4:1184: AC_LIBTOOL_SYS_HARD_LINK_LOCKS is expanded from...
build/libtool.m4:2809: _LT_AC_LANG_CXX_CONFIG is expanded from...
build/libtool.m4:2808: AC_LIBTOOL_LANG_CXX_CONFIG is expanded from...
build/libtool.m4:1917: _LT_AC_TAGCONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
configure.ac:161: warning: back quotes and double quotes must not be escaped in: $as_me: WARNING: \`$CC' does not support \`-c -o', so \`make -j' may be unsafe
build/libtool.m4:1184: AC_LIBTOOL_SYS_HARD_LINK_LOCKS is expanded from...
build/libtool.m4:2809: _LT_AC_LANG_CXX_CONFIG is expanded from...
build/libtool.m4:2808: AC_LIBTOOL_LANG_CXX_CONFIG is expanded from...
build/libtool.m4:1917: _LT_AC_TAGCONFIG is expanded from...
build/libtool.m4:70: AC_LIBTOOL_SETUP is expanded from...
build/libtool.m4:52: _AC_PROG_LIBTOOL is expanded from...
build/libtool.m4:39: AC_PROG_LIBTOOL is expanded from...
configure.ac:161: the top level
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for pkg-config... /opt/homebrew/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether cc accepts -g... yes
checking for cc option to enable C11 features... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... aarch64-apple-darwin22.2.0
checking host system type... aarch64-apple-darwin22.2.0
checking target system type... aarch64-apple-darwin22.2.0
checking for PHP prefix... /Users/<user>/.phpbrew/php/php-7.4.27
checking for PHP includes... -I/Users/<user>/.phpbrew/php/php-7.4.27/include/php -I/Users/<user>/.phpbrew/php/php-7.4.27/include/php/main -I/Users/<user>/.phpbrew/php/php-7.4.27/include/php/TSRM -I/Users/<user>/.phpbrew/php/php-7.4.27/include/php/Zend -I/Users/<user>/.phpbrew/php/php-7.4.27/include/php/ext -I/Users/<user>/.phpbrew/php/php-7.4.27/include/php/ext/date/lib
checking for PHP extension directory... /Users/<user>/.phpbrew/php/php-7.4.27/lib/php/extensions/no-debug-non-zts-20190902
checking for PHP installed headers prefix... /Users/<user>/.phpbrew/php/php-7.4.27/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking for ssh2 support... yes, shared
checking for ssh2 files in default path... not found
configure: error: The required libssh2 library was not found.  You can obtain that package from http://sourceforge.net/projects/libssh2/
```

</details>

### Platform

OS:
MacOS 13.1, M1

Running PHP: 
`7.4.27`

Installing PHP:
`7.4.27`

**Comment by PPP01** [comment]
I have the same problem!
--with-password-argon2 \
--with-gmp \
--with-sodium

None of these parameters works.

**Comment by PPP01** [comment]
I tested with phpbrew-1.28.0.phar now, too. It throws many warnings, but the result works.

Platform
OS:
Ubuntu 20.04

Running PHP:
PHP 8.1.9

Installing PHP:
PHP 8.1.14

**Comment by PPP01** [comment]
CONFIGURE_COMMAND with phpbrew-1.28.0

`CONFIGURE_COMMAND = './configure' '--cache-file=/opt/phpbrew/cache/config.cache' '--prefix=/opt/phpbrew/php/php-8.1.14' '--disable-all' '--enable-phar' '--enable-session' '--enable-short-tags' '--enable-tokenizer' '--with-zlib=/usr' '--with-libdir=lib/x86_64-linux-gnu' '--enable-exif' '--enable-intl' '--with-mysqli=mysqlnd' '--with-pdo-mysql' '--with-sqlite3' '--with-pdo-sqlite' '--enable-ftp' '--enable-soap' '--with-tidy' '--with-iconv' '--with-gettext=/usr' '--with-openssl' '--enable-opcache' '--enable-dom' '--with-libxml' '--enable-simplexml' '--enable-xml' '--enable-xmlreader' '--enable-xmlwriter' '--with-xsl' '--enable-bcmath' '--with-bz2=/usr' '--enable-calendar' '--enable-cli' '--enable-ctype' '--enable-fileinfo' '--enable-filter' '--enable-shmop' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-json' '--enable-mbregex' '--enable-mbstring' '--with-mhash=/usr' '--enable-pcntl' '--enable-pdo' '--with-pear=/opt/phpbrew/php/php-8.1.14/lib/php/pear' '--enable-posix' '--with-readline=/usr' '--enable-sockets' '--with-curl' '--with-zip' '--enable-gd' '--with-jpeg=/usr/lib/x86_64-linux-gnu/' '--with-xpm=/usr/lib/x86_64-linux-gnu/' '--with-webp=/usr/lib/x86_64-linux-gnu/' '--with-freetype=/usr/include/freetype2/' '--with-config-file-scan-dir=/opt/phpbrew/php81.ini.d' '--with-mysql-sock=/var/run/mysqld/mysqld.sock' '--with-password-argon2' '--with-gmp' '--with-sodium' '--with-config-file-path=/opt/phpbrew/php/php-8.1.14/etc/cli' '--with-config-file-scan-dir=/opt/phpbrew/php/php-8.1.14/var/db/cli' 'PKG_CONFIG_PATH=/usr/lib/pkgconfig'`

CONFIGURE_COMMAND with phpbrew-1.28.0

`CONFIGURE_COMMAND = './configure' '--cache-file=/opt/phpbrew/cache/config.cache' '--prefix=/opt/phpbrew/php/php-8.1.14' '--disable-all' '--enable-phar' '--enable-session' '--enable-short-tags' '--enable-tokenizer' '--with-zlib=/usr' '--with-libdir=lib/x86_64-linux-gnu' '--enable-exif' '--enable-intl' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--with-mysql-sock=/var/run/mysqld/mysqld.sock' '--with-sqlite3' '--with-pdo-sqlite' '--enable-ftp' '--enable-soap' '--with-tidy' '--with-iconv' '--with-gettext=/usr' '--with-openssl' '--enable-opcache' '--enable-dom' '--with-libxml' '--enable-simplexml' '--enable-xml' '--enable-xmlreader' '--enable-xmlwriter' '--with-xsl' '--enable-bcmath' '--with-bz2=/usr' '--enable-calendar' '--enable-cli' '--enable-ctype' '--enable-fileinfo' '--enable-filter' '--enable-shmop' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-json' '--enable-mbregex' '--enable-mbstring' '--with-mhash=/usr' '--enable-pcntl' '--enable-pdo' '--with-pear=/opt/phpbrew/php/php-8.1.14/lib/php/pear' '--enable-posix' '--with-readline=/usr' '--enable-sockets' '--with-curl' '--with-zip' '--with-config-file-path=/opt/phpbrew/php/php-8.1.14/etc/cli' '--with-config-file-scan-dir=/opt/phpbrew/php/php-8.1.14/var/db/cli' 'PKG_CONFIG_PATH=/usr/lib/pkgconfig'`

Comand:
`phpbrew install -j $(nproc) 8.1.14 +default +exif +fpm +intl +mysql +sqlite +ftp +soap +tidy +iconv +gettext +openssl +opcache \
-- --enable-gd \
--with-jpeg=/usr/lib/x86_64-linux-gnu/ \
--with-xpm=/usr/lib/x86_64-linux-gnu/ \
--with-webp=/usr/lib/x86_64-linux-gnu/ \
--with-freetype=/usr/include/freetype2/  \
--with-config-file-scan-dir=/opt/phpbrew/php81.ini.d \
--with-pdo-mysql --with-mysql-sock=/var/run/mysqld/mysqld.sock \
--with-password-argon2 \
--with-gmp \
--with-sodium`

**Comment by theofidry** [comment]
I can confirm I have the same problem

**Comment by peter279k** [comment]
The issue is verified and it will be fixed in the next released version.

**Comment by PPP01** [comment]
Hi, there is still a problem with v.1.28.0 and v.2.0
'--with-config-file-path=' and '--with-config-file-scan-dir' is put at the end of the config chain. This overwrites the configured values.
In v.1.27 both flags were at the beginning of the chain, so they were overwritten by the own config. 
Should I open a new ticket for this or is this already fixed by the patch?

**Comment by peter279k** [comment]
> Hi, there is still a problem with v.1.28.0 and v.2.0 '--with-config-file-path=' and '--with-config-file-scan-dir' is put at the end of the config chain. This overwrites the configured values. In v.1.27 both flags were at the beginning of the chain, so they were overwritten by the own config. Should I open a new ticket for this or is this already fixed by the patch?

I think the issue is related to another one. Please create a new issue to describe more details. Thanks.

**Comment by peter279k** [comment]
@MagicLegend and @PPP01, could you help me to use the latest `2.1.0` version to check the issue is resolved?

I use your problematic commands and it's resolved in the `2.1.0` version.

If having any issue, don't hesitate to let me know. 

Thanks!

**Comment by ioweb-gr** [comment]
For me it seems to proceed but it still cannot compile with +fpm argument

```
phpbrew --debug install --patch freetype.patch 7.2.34 +default +small +mb +dbs +fpm -wddx +openssl=/opt/openssl/1.1.1i -- --with-pspell --disable-shmop  --with-curl=/opt/curl/7.58 --with-openssl as phpbrew7_2_34_fdev
*WARNING* You're running phpbrew as root/sudo. Unless you're going to install system-wide phpbrew, this might cause problems.
===> phpbrew will now build 7.2.34 as phpbrew7_2_34_fdev
---> Parsing variants from command arguments '+default +small +mb +dbs +fpm -wddx +openssl=/opt/openssl/1.1.1i -- --with-pspell --disable-shmop --with-curl=/opt/curl/7.58 --with-openssl'
===> Loading and resolving variants...
Checking distribution checksum...
Checksum matched: 0e5816d668a2bb14aca68cef8c430430bd86c3c5233f6c427d1a54aac127abcf
===> Extracting /root/.phpbrew/distfiles/php-7.2.34.tar.bz2 to /root/.phpbrew/build/tmp.1681465103/php-7.2.34
===> Moving /root/.phpbrew/build/tmp.1681465103/php-7.2.34 to /root/.phpbrew/build/phpbrew7_2_34_fdev
Source Directory: /root/.phpbrew/build/phpbrew7_2_34_fdev
Writing variant info to /root/.phpbrew/php/phpbrew7_2_34_fdev/phpbrew.variants
Running make clean to ensure everything will be rebuilt.
Makefile not found in path /root/.phpbrew/build/phpbrew7_2_34_fdev
===> Applying patch file from /root/freetype.patch ...
patching file ext/gd/config.m4
Hunk #1 succeeded at 186 (offset 2 lines).
===> Checking patches...
Checking patch for replace apache php module name with custom version name
Checking patch for replace freetype-config with pkg-config on php older than 7.4
Checking patch for fix readline detection on PHP 5.3 to PHP 7.1
---> Applying patch...
patching file ext/readline/config.m4
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file ext/readline/config.m4.rej

Patch failed
0 changes patched.
Enabled variants: [fpm, openssl, xml, opcache, sqlite, mysql, pgsql, pdo, mbstring, mbregex, bz2, cli, dom, filter, ipc, json, pcre, phar, posix, readline, curl, bcmath, calendar, ctype, fileinfo, mhash, pcntl, pear, sockets, tokenizer, zip]
Disabled variants: [wddx]
===> Configuring 7.2.34...


Use tail command to see what's going on:
   $ tail -F '/root/.phpbrew/build/phpbrew7_2_34_fdev/build.log'


./configure '--cache-file=/root/.phpbrew/cache/config.cache' '--prefix=/root/.phpbrew/php/phpbrew7_2_34_fdev' '--disable-all' '--enable-phar' '--enable-session' '--enable-short-tags' '--enable-tokenizer' '--with-pcre-regex' '--with-zlib=/usr' '--with-libdir=lib/x86_64-linux-gnu' '--with-openssl' '--enable-dom' '--enable-libxml' '--with-libxml-dir=/usr' '--enable-simplexml' '--enable-xml' '--enable-xmlreader' '--enable-xmlwriter' '--with-xsl' '--enable-opcache' '--with-sqlite3' '--with-pdo-sqlite' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--with-mysql-sock=/var/run/mysqld/mysqld.sock' '--with-pgsql=/usr/bin' '--with-pdo-pgsql=/usr/bin' '--enable-pdo' '--enable-mbstring' '--enable-mbregex' '--with-bz2=/usr' '--enable-cli' '--enable-filter' '--enable-shmop' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-json' '--with-pcre-dir=/usr' '--enable-posix' '--with-readline=/usr' '--with-curl=/usr/local' '--enable-bcmath' '--enable-calendar' '--enable-ctype' '--enable-fileinfo' '--with-mhash=/usr' '--enable-pcntl' '--with-pear=/root/.phpbrew/php/phpbrew7_2_34_fdev/lib/php/pear' '--enable-sockets' '--enable-zip' '--disable-wddx' '--with-pspell' '--disable-shmop' '--with-curl=/opt/curl/7.58' '--with-config-file-path=/root/.phpbrew/php/phpbrew7_2_34_fdev/etc/cli' '--with-config-file-scan-dir=/root/.phpbrew/php/phpbrew7_2_34_fdev/var/db/cli' 'PKG_CONFIG_PATH=/opt/openssl-1.1.1i/bin/lib/pkgconfig' >> '/root/.phpbrew/build/phpbrew7_2_34_fdev/build.log' 2>&1
===> Checking patches...
Checking patch for php5.3.x on 64bit machine when intl is enabled.
Checking patch for openssl dso linking patch
Checking patch for php5.6 with openssl 1.1.x patch.
===> Building...
make >> '/root/.phpbrew/build/phpbrew7_2_34_fdev/build.log' 2>&1
Build finished: 7.5 minutes.
Installing...
---> Creating php.ini
---> Copying /root/.phpbrew/build/phpbrew7_2_34_fdev/php.ini-development
---> Found date.timezone is not set, patching...
Running make clean to ensure everything will be rebuilt.
===> Running make clean: /usr/bin/make -C '/root/.phpbrew/build/phpbrew7_2_34_fdev' --quiet 'clean'
Running Command:/usr/bin/make -C '/root/.phpbrew/build/phpbrew7_2_34_fdev' --quiet 'clean'
===> Applying patch file from /root/freetype.patch ...
===> Checking patches...
Checking patch for replace apache php module name with custom version name
Checking patch for replace freetype-config with pkg-config on php older than 7.4
Checking patch for fix readline detection on PHP 5.3 to PHP 7.1
---> Applying patch...
patching file ext/readline/config.m4
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file ext/readline/config.m4.rej

Patch failed
0 changes patched.
Enabled variants: [fpm, openssl, xml, opcache, sqlite, mysql, pgsql, pdo, mbstring, mbregex, bz2, cli, dom, filter, ipc, json, pcre, phar, posix, readline, curl, bcmath, calendar, ctype, fileinfo, mhash, pcntl, pear, sockets, tokenizer, zip]
Disabled variants: [wddx]
Found existing build.log, renaming it to /root/.phpbrew/build/phpbrew7_2_34_fdev/build.log.1681465579
===> Configuring 7.2.34...


Use tail command to see what's going on:
   $ tail -F '/root/.phpbrew/build/phpbrew7_2_34_fdev/build.log'


./configure '--cache-file=/root/.phpbrew/cache/config.cache' '--prefix=/root/.phpbrew/php/phpbrew7_2_34_fdev' '--disable-all' '--enable-phar' '--enable-session' '--enable-short-tags' '--enable-tokenizer' '--with-pcre-regex' '--with-zlib=/usr' '--with-libdir=lib/x86_64-linux-gnu' '--with-openssl' '--enable-dom' '--enable-libxml' '--with-libxml-dir=/usr' '--enable-simplexml' '--enable-xml' '--enable-xmlreader' '--enable-xmlwriter' '--with-xsl' '--enable-opcache' '--with-sqlite3' '--with-pdo-sqlite' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--with-mysql-sock=/var/run/mysqld/mysqld.sock' '--with-pgsql=/usr/bin' '--with-pdo-pgsql=/usr/bin' '--enable-pdo' '--enable-mbstring' '--enable-mbregex' '--with-bz2=/usr' '--enable-filter' '--enable-shmop' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-json' '--with-pcre-dir=/usr' '--enable-posix' '--with-readline=/usr' '--with-curl=/usr/local' '--enable-bcmath' '--enable-calendar' '--enable-ctype' '--enable-fileinfo' '--with-mhash=/usr' '--enable-pcntl' '--with-pear=/root/.phpbrew/php/phpbrew7_2_34_fdev/lib/php/pear' '--enable-sockets' '--enable-zip' '--disable-wddx' '--with-pspell' '--disable-shmop' '--with-curl=/opt/curl/7.58' '--with-config-file-path=/root/.phpbrew/php/phpbrew7_2_34_fdev/etc/fpm' '--with-config-file-scan-dir=/root/.phpbrew/php/phpbrew7_2_34_fdev/var/db/fpm' '--enable-fpm' '--with-fpm-systemd' '--disable-cli' 'PKG_CONFIG_PATH=/opt/openssl-1.1.1i/bin/lib/pkgconfig' >> '/root/.phpbrew/build/phpbrew7_2_34_fdev/build.log' 2>&1
Error: Configure failed:
The last 5 lines in the log file:
checking for sd_notify in -lsystemd-daemon... no

checking systemd/sd-daemon.h usability... no

checking systemd/sd-daemon.h presence... no

checking for systemd/sd-daemon.h... no

configure: error: Your system does not support systemd.

Please checkout the build log file for more details:
         tail /root/.phpbrew/build/phpbrew7_2_34_fdev/build.log
```

It seems the arguments are passed correctly now so it's finding openssl and curl but still not fully working :(

**Comment by MagicLegend** [comment]
@peter279k Thank you, it looks fine with `2.1.0` :-)
