### ISSUE TITLE
libicu header files can't be found on Ubuntu 64bit without specifying prefix

### ISSUE THREAD

**Issue by c9s** [phpbrew/phpbrew#433]
```
phpbrew  install 5.6 +pdo +mysql +pgsql=/opt/local/lib/postgresql92/bin  +fpm +sqlite +pcntl               +posix +gettext +intl +openssl +default +curl +readline +session +xml_all               +phpdbg +soap +bcmath +exif +fileinfo +ipc +imap +mbregex +mbstring +mhash               +opcache +xml +zts +icu

....cut
checking for location of ICU headers and libraries... not found
configure: error: Unable to detect ICU prefix or /usr/lib/x86_64-linux-gnu/bin/icu-config failed. Please verify ICU install prefix and make sure icu-config works.
```

```
$ which icu-config
/usr/bin/icu-config
```

however this works:

```
phpbrew  install 5.6 +pdo +mysql  +fpm +sqlite +pcntl               \
  +posix +gettext +intl +openssl +default +curl +readline +session +xml_all         \
  +phpdbg +soap +bcmath +exif +fileinfo +ipc +imap +mbregex +mbstring +mhash     \
  +opcache +xml +zts +icu -- --with-icu-dir=/usr
```

**Comment by mdkholy** [comment]
same here

**Comment by jmacloue** [comment]
Yeap, phpbrew's detection of icu-config location is weird, and when it sees +icu on command line it inserts its own version of `--with-icu-dir` before the one given after `--`, excerpt from config.log:

`$ ./configure ... --with-icu-dir=/usr/lib64 ... --with-icu-dir=/usr`

The former takes precedence and PHP looks for icu-config under weird `/usr/lib64/bin/icu-config` path (Slackware64 here but saw this on CentOS and RHEL 64-bit also).

The workaround is rather trivial - just drop the `+icu` part and leave `+intl` as it is. If your icu-config is in the PATH - PHP will happily use it, if not - force it with ` -- ICU_CONFIG=/path/to/your/icu-config`

Another possible workaround is giving the correct ICU prefix as `+icu=/usr` or something like that, the code in ./src/PhpBrew/VariantBuilder.php from line 279 suggests it should work. Didn't try it though.

**Comment by c9s** [comment]
This might be related to multiarch

And `icu-config --prefix` dumps empty lines at the end, therefore we can't just use `system()` to get the last line from the output.

**Comment by jmacloue** [comment]
Well, why not use exec() instead?

```
diff --git a/src/PhpBrew/VariantBuilder.php b/src/PhpBrew/VariantBuilder.php
index cac7bcc..d765534 100644
--- a/src/PhpBrew/VariantBuilder.php
+++ b/src/PhpBrew/VariantBuilder.php
@@ -352,6 +352,14 @@ class VariantBuilder
             if ($val) {
                 return '--with-icu-dir=' . $val;
             }
+
+           // Ask icu-config if present
+           $icu_prefix = array();
+           exec("icu-config --prefix", $icu_prefix, $retcode);
+           if ($retcode == 0) {
+               return '--with-icu-dir=' . $icu_prefix[0];
+           }
+
             // the last one path is for Ubuntu
             if ($prefix = Utils::findLibPrefix('icu/pkgdata.inc', 'icu/Makefile.inc')) {
                 return '--with-icu-dir=' . $prefix;

```
But, well, I'd suggest to get rid of everything except the first ``if`` construction here as PHP's ``configure`` script is capable enough to locate libicu on its own - so why bother at all? Keeping ``+icu=/usr/local`` may help in some non-standard situations when a custom ``--with-icu-dir`` is needed, on the other hand.

**Comment by c9s** [comment]
Homebrew uses it's own path, we still need to execute brew --prefix to get the correct prefix if icu-config is not found.

**Comment by c9s** [comment]
./configure sometimes only looks for /usr or /usr/local.  `/opt/local` is not searched.

**Comment by jmacloue** [comment]
That's where ``+icu=/opt/local`` is appropriate, as I said.

The ``--with-icu-dir=PATH`` option is actually to help ``configure`` locate the libicu if it doesn't. This switch doesn't control any of the PHP's features directly so I'd suggest omitting it by default: it works out of the box most of the time. So, adding just ``+intl`` to phpbrew invocation usually works fine, and adding ``+icu=/opt/local`` is for those who have libicu installed in a non-standard way (and this crowd is usually tech-savvy enough to recognize the need to give an argument here). Unfortunately there are some guides over the Internet which have ``+icu`` without arguments added for some reason, and most of the time people who follows those guides are not savvy enough to understand the problem.

PS And, well, if phpbrew messes with PATH so that ``icu-config`` cannot be found under ``phpbrew`` but it is found without it - so ``phpbrew`` is wrong and must be fixed.

**Comment by c9s** [comment]
make sense.

`--with-icu-dir=/usr/lib64` this looks like should be `--with-lib-dir=/usr/lib64` ?

**Comment by c9s** [comment]
I think the most annoying part is multiarch,   linux supports multiarch, so library could be located in the following paths

```
            /usr/lib/i386-linux-gnu/
            /usr/include/i386-linux-gnu/
            /usr/lib/x86_64-linux-gnu/
            /usr/local/lib/powerpc-linux-gnu/
            /usr/local/include/powerpc-linux-gnu/
            /opt/foo/lib/sparc-solaris/
            /opt/bar/include/sparc-solaris/
```

but if icu already provides `--icu-config` it think it will work fine without handling multiarch.

**Comment by c9s** [comment]
I updated the phar file with this fix, please try `phpbrew self-update develop` to confirm this fix. :)

**Comment by c9s** [comment]
let me summarize the current logic,

1. if `icu` variant is not given and `--with-icu-dir` is not provided in the extra options
  1. If `icu-config` could be found, let autoconf to find the icu-config by itself.
  2. If `icu-config` couldn't be found
     1. first check icu from pkg-config
     2. find icu-config from brew --prefx

**Comment by c9s** [comment]
Done

**Comment by azrek** [comment]
I found this to be still an issue when building php5.3.25:

* phpbrew install 5.3.25 +default+dbs+apxs2

Don't go down the path of install brew (as suggested in the Troubleshooting page: https://github.com/phpbrew/phpbrew/wiki/TroubleShooting ) !! What a disaster. 

What solved it for me was just:

sudo apt-get install libicu-dev

Obviously Ubuntu...

Hope this helps someone!

Cheers.

**Comment by Nukium** [comment]
> The workaround is rather trivial - just drop the `+icu` part and leave `+intl` as it is. If your icu-config is in the PATH - PHP will happily use it, if not - force it with `-- ICU_CONFIG=/path/to/your/icu-config`
> 

Thanks !
