### ISSUE TITLE
Can't start fpm on 7.2.0

### ISSUE THREAD

**Issue by alpipego** [phpbrew/phpbrew#938]
### Output

```
phpbrew fpm start
Starting php-fpm...
Usage: php-fpm [-n] [-e] [-h] [-i] [-m] [-v] [-t] [-p <prefix>] [-g <pid>] [-c <file>] [-d foo[=bar]] [-y <file>] [-D] [-F [-O]]
  -c <path>|<file> Look for php.ini file in this directory
  -n               No php.ini file will be used
  -d foo[=bar]     Define INI entry foo with value 'bar'
  -e               Generate extended information for debugger/profiler
  -h               This help
  -i               PHP information
  -m               Show compiled in modules
  -v               Version number
  -p, --prefix <dir>
                   Specify alternative prefix path to FastCGI process manager (default: /home/vagrant/.phpbrew/php/php-7.2.0).
  -g, --pid <file>
                   Specify the PID file location.
  -y, --fpm-config <file>
                   Specify alternative path to FastCGI process manager config file.
  -t, --test       Test FPM configuration and exit
  -D, --daemonize  force to run in background, and ignore daemonize option from config file
  -F, --nodaemonize
                   force to stay in foreground, and ignore daemonize option from config file
  -O, --force-stderr
                   force output to stderr in nodaemonize even if stderr is not a TTY
  -R, --allow-to-run-as-root
                   Allow pool to run as root (disabled by default)
php-fpm start failed.
```

### Installation

```
phpbrew install 7.2.0 +default+fpm+mysql+gd+openssl=shared -- --with-openssl
```

`phpbrew fpm test` output 

```
NOTICE: configuration file /home/vagrant/.phpbrew/php/php-7.2.0/etc/php-fpm.conf test is successful
```

It works fine with several other php versions, just not with php 7.2.0

**Comment by morozov** [comment]
@alpipego this must have been resolved in #867. Please make sure you're using the latest PHPBrew release and your `~/.phpbrew/bashrc` is up to date.

**Comment by alpipego** [comment]
@morozov thanks, I already had the latest version. Also applying the patch manually, unfortunately, does not fix this for me.

**Comment by morozov** [comment]
> Also applying the patch manually, unfortunately, does not fix this for me.

Were you able to patch `~/.phpbrew/bashrc` or it was already up to date? If you patched the file, make sure you have started a new shell before testing the changes.

If you want to debug it, this is the code block you want to look at:

https://github.com/phpbrew/phpbrew/blob/cdc1f54cde3c1c698754fd8f959ffb6b7ca0c292/shell/bashrc#L225-L234

On any PHP version newer than 5.2, the command in the `else` block should be executed.

**Comment by alpipego** [comment]
Thank you for the reply. After restarting the server it does work! 💯
(I thought, I had sourced `.bashrc` afterward...). Thanks.
